theme: jekyll-theme-architect
title: (* STAR Teknoloji 
description: Star* Teknoloji Hizmetinizde Hoşgeldiniz. Google Haritalar ve Github Sayfalarında Bulabilirsiniz. Bİze Ayırdığınız Vakit için Teşekkür ederiz.
yazar:  Erçetin Güler
